//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 EasyPuTTY.rc 使用
//
#define IDC_MYICON                      2
#define IDD_EASYPUTTY_DIALOG            102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    104
#define IDM_TABMENU                     105
#define IDM_ABOUT                       106
#define IDM_EXIT                        107
#define IDI_EASYPUTTY                   108
#define IDC_EASYPUTTY                   110
#define IDR_MAINFRAME                   128
#define IDR_MAIN_TOOLBAR                129
#define IDD_ATTACH                      131
#define IDD_CREDENTIAL                  132
#define IDD_ENUMWIN                     133
#define IDD_SESSION                     134
#define IDD_SETTING                     135
#define IDR_SESSION                     136
#define IDD_PROGRAM                     137
#define IDD_DIALOG1                     138
#define IDD_RENAME                      139
#define IDC_REFRESH                     1001
#define IDC_BROWSER_PUTTY               1002
#define IDC_SYSLINK1                    1003
#define IDC_BUTTON2                     1004
#define IDC_EDIT                        1004
#define IDC_BROWSER_WINSCP              1005
#define IDC_SYSLINK2                    1006
#define IDC_BROWSER_FILEZILLA           1007
#define IDC_SESSION_NAME                1008
#define IDC_PUTTY                       1009
#define IDC_SESSION_IP                  1010
#define IDC_WINSCP                      1011
#define IDC_SESSION_PORT                1012
#define IDC_FILEZILLA                   1013
#define IDC_SESSION_CONNECT             1014
#define IDC_USERNAME                    1015
#define IDC_BROWSER_PAGEANT             1016
#define IDC_SESSION_CREDENTIAL          1017
#define IDC_BROWSER                     1018
#define IDC_BROWSER_PUTTYGEN            1019
#define IDC_CREDENTIAL_ADD              1020
#define IDC_PUTTY_PARAMS                1021
#define IDC_TAGS                        1022
#define IDC_PAGEANT                     1023
#define IDC_PASSWORD                    1024
#define IDC_PUTTYGEN                    1025
#define IDC_EDIT1                       1026
#define IDC_PSFTP                       1026
#define IDC_OTHER_PARAMS                1027
#define IDC_PRO_NAME                    1028
#define IDC_TAG_NAME                    1029
#define IDC_NAME                        1030
#define IDC_PRO_PATH                    1031
#define IDC_PPK                         1032
#define IDC_PRO_PARAM                   1033
#define IDC_EDIT4                       1034
#define IDC_PRO_TAGS                    1035
#define IDC_BUTTON1                     1036
#define IDC_BROWSER_PSFTP               1036
#define IDC_DEL                         1037
#define IDC_LIST_NAME                   1038
#define IDC_CLEAR                       1039
#define IDC_RESET                       1040
#define IDC_BUTTON3                     1041
#define IDC_ADD                         1042
#define ID_SEARCH_EDIT                  1043
#define ID_SEARCH_BUTTON                1044
#define IDM_OPEN                        32771
#define IDM_CLOSE                       32772
#define IDM_ENUM_WINDOW                 32773
#define ID_ENUM_VIEW                    32774
#define ID_ENUM_ATTACH                  32775
#define ID_LIST_VIEW                    32776
#define ID_LIST_ATTACH                  32777
#define ID_TAB_CLOSE                    32778
#define ID_TAB_MOVETOLEFT               32779
#define ID_LIST_DEL                     32780
#define ID_TAB_MOVETORIGHT              32781
#define ID_TAB_MOVETOLEFTMOST           32782
#define ID_TAB_MOVETORIGHTMOST          32783
#define ID_Menu                         32784
#define ID_DEATCH                       32785
#define ID_TAB_DETACH                   32786
#define ID_TODO                         32787
#define IDM_SETTING                     32788
#define IDM_SESSION                     32789
#define IDM_CREDENTIAL                  32790
#define IDM_PAGEANT                     32791
#define IDM_PUTTYGEN                    32792
#define ID_PUTTY                        32793
#define ID_RUN_COMMAND                  32794
#define IDM_PROGRAM                     32795
#define ID_LIST_WINSCP                  32796
#define ID_LIST_FILEZILLA               32797
#define ID_LIST_EDIT                    32798
#define ID_TAB_REFRESH                  32799
#define ID_TAB_DETACH_ALL               32800
#define ID_LIST_REFRESH                 32801
#define ID_TAB_AUTO                     32802
#define ID_TAB_CLONE                    32803
#define ID_TAB_RENAME                   32804
#define ID_TAB_RENAME_GET               32805
#define ID_TAB_32807                    32806
#define ID_TAB_RENAME_DO                32807
#define ID_TAB_CLOSE_RIGHT              32808
#define ID_TAB_CLOSE_OTHER              32809
#define ID_TAB_CLOSE_ALL                32810
#define ID_PUTTY_PSFTP                  32811
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32812
#define _APS_NEXT_CONTROL_VALUE         1045
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
