//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 EasyPuTTY.rc 使用
//
#define IDC_MYICON                      2
#define IDC_EASYPUTTY                   100
#define IDC_TABCONTROL                  101
#define IDD_EASYPUTTY_DIALOG            102
#define IDD_ABOUTBOX                    103
#define IDM_TABMENU                     104
#define IDM_TABMENU_EN                  105
#define IDM_ABOUT                       106
#define IDM_EXIT                        107
#define IDI_EASYPUTTY                   108
#define IDR_MAINFRAME                   128
#define IDR_MAIN_TOOLBAR                129
#define IDD_ATTACH                      131
#define IDD_CREDENTIAL                  132
#define IDD_ENUMWIN                     133
#define IDD_SESSION                     134
#define IDD_SETTING                     135
#define IDR_SESSION                     136
#define IDR_SESSION_EN                  137
#define IDD_PROGRAM                     138
#define IDD_DIALOG1                     139
#define IDD_RENAME                      140
#define IDD_PAGEANT                     141
#define IDC_REFRESH                     1001
#define IDC_BROWSER_PUTTY               1002
#define IDC_SYSLINK1                    1003
#define IDC_BUTTON2                     1004
#define IDC_EDIT                        1004
#define IDC_CLEAN                       1004
#define IDC_BROWSER_WINSCP              1005
#define IDC_SYSLINK2                    1006
#define IDC_BROWSER_FILEZILLA           1007
#define IDC_SESSION_NAME                1008
#define IDC_PUTTY                       1009
#define IDC_SESSION_IP                  1010
#define IDC_WINSCP                      1011
#define IDC_SESSION_PORT                1012
#define IDC_FILEZILLA                   1013
#define IDC_SESSION_CONNECT             1014
#define IDC_USERNAME                    1015
#define IDC_BROWSER_PAGEANT             1016
#define IDC_SESSION_CREDENTIAL          1017
#define IDC_BROWSER                     1018
#define IDC_BROWSER_PUTTYGEN            1019
#define IDC_CREDENTIAL_ADD              1020
#define IDC_PUTTY_PARAMS                1021
#define IDC_TAGS                        1022
#define IDC_PAGEANT                     1023
#define IDC_PASSWORD                    1024
#define IDC_PUTTYGEN                    1025
#define IDC_EDIT1                       1026
#define IDC_PSFTP                       1026
#define IDC_OTHER_PARAMS                1027
#define IDC_PRO_NAME                    1028
#define IDC_TAG_NAME                    1029
#define IDC_NAME                        1030
#define IDC_PRO_PATH                    1031
#define IDC_PPK                         1032
#define IDC_PRO_PARAM                   1033
#define IDM_DEBUG                       1034
#define IDC_PRO_TAGS                    1035
#define IDC_BUTTON1                     1036
#define IDC_BROWSER_PSFTP               1036
#define IDC_DEL                         1037
#define IDC_LIST_NAME                   1038
#define IDC_CLEAR                       1039
#define IDC_RESET                       1040
#define IDC_BUTTON3                     1041
#define IDC_ADD                         1042
#define ID_SEARCH_EDIT                  1043
#define ID_SEARCH_BUTTON                1044
#define IDC_PAGEANT_STATUS              1045
#define IDC_INPUT                       1046

// 字符串ID定义
#define IDS_APP_TITLE                   2001
#define IDS_TAB_NEW                     2002
#define IDS_MENU_ATTACH                 2003
#define IDS_MSG_CREATE_FAILED           2004
#define IDS_LIST_PID                    2005
#define IDS_LIST_TITLE                  2006
#define IDS_LIST_PROCESS                2007
#define IDS_LIST_PATH                   2008
#define IDS_BTN_OK                      2009
#define IDS_BTN_CANCEL                  2010
#define IDS_TIP_CONFIRM_PASTE           2011
#define IDS_TIP_CLIPBOARD_LEN           2012
#define IDS_MENU_FILE                   2013
#define IDS_MENU_HELP                   2014
#define IDS_TAB_CLOSE_TITLE             2016
#define IDS_TAB_CLOSE_TIP               2017
#define IDS_MESSAGE_CAPTION             2018
#define IDS_NEED_COMMAND                2019
#define IDS_TIP_CONFIRM_CLOSE           2020
#define IDS_TIP_CLOSE_APP               2021
#define IDS_TAB_CLONE_FAIL              2022
#define IDS_TAB_CREATE_FAIL             2023
#define IDS_TOOLBAR_CREATE              2024
#define IDS_TOOLBAR_SPLIT               2025
#define IDS_TOOLBAR_WINDOW              2026
#define IDS_TOOLBAR_SESSION             2027
#define IDS_TOOLBAR_CREDENTIAL          2028
#define IDS_TOOLBAR_PAGEANT	            2029
#define IDS_TOOLBAR_PUTTYGEN            2030
#define IDS_TOOLBAR_SETTING             2031
#define IDS_TOOLBAR_PROGRAM             2032
#define IDS_TOOLBAR_DEBUG               2033
#define IDS_TOOLBAR_ABOUT               2034
#define IDS_BTN_CLEAR                   2035
#define IDS_TAB_UNTITLED                2036
#define IDS_HOSTWINDOW_FAIL             2037
#define IDS_REGISTER_WNDCLASS_FAIL      2038
#define IDS_LOG_WINDOW_FAIL             2039
#define IDS_PROCESS_FAIL                2040
#define IDS_LISTVIEW_FAIL               2041
#define IDS_CUSTOM                      2042
#define IDS_NONE                        2043
#define IDS_NAME                        2044
#define IDS_TYPE                        2045
#define IDS_COMMAND                     2046
#define IDS_TAG                         2047
#define IDS_CREDENTIAL                  2048
#define IDS_INPUT                       2049
#define IDS_PROCESS_START_FAIL          2050
#define IDS_PROCESS_STARTING            2051
#define IDS_PROCESS_STARTED             2052
#define IDS_PROCESS_NOT_STARTED         2053
#define IDS_NAME_REQUIRED               2054
#define IDS_HOSTNAME_REQUIRED           2055
#define IDS_ADD_FAIL                    2056
#define IDS_BROWSER_EXE                 2057
#define IDS_BROWSER_PPK                 2058
#define IDS_BROWSER_REQUIRED            2059
#define IDS_ERROR_FORMAT                2060
#define IDS_BROWSER_COM                 2061
#define IDS_ACCESS_FAIL                 2062
#define IDS_UNKNOWN                     2063
#define IDS_FILEZILLA_PATH              2064
#define IDS_FILEZILLA_TIPS              2065
#define IDS_WINSCP_PATH                 2066
#define IDS_PSFTP_PATH                  2067
#define IDS_NOT_PUTTY_TIPS              2068
#define IDS_DEBUG_TITLE                 2070
#define IDD_ABOUTBOX_EN                 2071
#define IDD_PAGEANT_EN                  2072
#define IDD_SESSION_EN                  2073
#define IDD_CREDENTIAL_EN               2074
#define IDD_SETTING_EN                  2075
#define IDD_PROGRAM_EN                  2076
#define IDD_RENAME_EN                   2077
#define IDD_ENUMWIN_EN                  2078
#define IDS_SPLIT_TITLE                 2079

#define IDM_OPEN                        32771
#define IDM_SPLIT                       32772
#define IDM_ENUM_WINDOW                 32773
#define ID_ENUM_VIEW                    32774
#define ID_ENUM_ATTACH                  32775
#define ID_LIST_VIEW                    32776
#define ID_LIST_ATTACH                  32777
#define ID_TAB_CLOSE                    32778
#define ID_TAB_MOVETOLEFT               32779
#define ID_LIST_DEL                     32780
#define ID_TAB_MOVETORIGHT              32781
#define ID_TAB_MOVETOLEFTMOST           32782
#define ID_TAB_MOVETORIGHTMOST          32783
#define ID_Menu                         32784
#define ID_DEATCH                       32785
#define ID_TAB_DETACH                   32786
#define ID_TODO                         32787
#define IDM_SETTING                     32788
#define IDM_SESSION                     32789
#define IDM_CREDENTIAL                  32790
#define IDM_PAGEANT                     32791
#define IDM_PUTTYGEN                    32792
#define ID_PUTTY                        32793
#define ID_RUN_COMMAND                  32794
#define IDM_PROGRAM                     32795
#define ID_LIST_WINSCP                  32796
#define ID_LIST_FILEZILLA               32797
#define ID_LIST_EDIT                    32798
#define ID_TAB_REFRESH                  32799
#define ID_TAB_DETACH_ALL               32800
#define ID_LIST_REFRESH                 32801
#define ID_TAB_AUTO                     32802
#define ID_TAB_CLONE                    32803
#define ID_TAB_RENAME                   32804
#define ID_TAB_RENAME_GET               32805
#define ID_TAB_32807                    32806
#define ID_TAB_RENAME_DO                32807
#define ID_TAB_CLOSE_RIGHT              32808
#define ID_TAB_CLOSE_OTHER              32809
#define ID_TAB_CLOSE_ALL                32810
#define ID_PUTTY_PSFTP                  32811
#define ID_HOTKEY_WINDOW                32812
#define ID_HOTKEY_NEW                   32813
#define ID_HOTKEY_CLOSE                 32814
#define ID_HOTKEY_SEARCH                32815
#define ID_HOTKEY_CLONE                 32816
#define ID_DEBUG_EDIT                   32817
#define ID_WINDOW_COMMAND               32818
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32819
#define _APS_NEXT_CONTROL_VALUE         1047
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
